sudo: required
dist: trusty

language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5

services:
  - docker

before_install:
  - docker pull elasticsearch
  - docker pull elubow/cassandra
  - docker pull davebshow/titan-websockets

install:
  - pip install -r requirements.txt
  - docker run -d --name es1 elasticsearch
  - docker run -d --name cas1 elubow/cassandra
  - docker run -d --name titan1 --link es1:elasticsearch --link cas1:cassandra -p 8182:8182 davebshow/titan-websockets

before_script:
  - sleep 30

script:
  - nosetests mogwai.tests.models.class_construction_tests
  - nosetests mogwai.tests.models.vertex_io_tests
  - nosetests mogwai.tests.models.edge_io_tests
  - nosetests mogwai.tests.properties_tests.validators_tests
  - nosetests mogwai.tests.properties_tests.value_manager_tests

after_success:
  - coveralls

deploy:
  provider: pypi
  username: platinummonkey
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    python: '2.7'
  password:
    secure: L0fqIUv7D60DIXLf5AnigKm4nyUIAieO5cfrpc7P8LhhuRAc+ZbSJmQd02EjwEoJouwV5tjMH28cJKuEwvq+RdtRTmlSQPgZKHs8Pk0IaljC2hy6RKIBU/zFJ9ycpERXdJMpbfl0LxwwJmeVo/2r8tA/nf5yuFzrrex3dKQxMOotWz9VS++LkvOMgXpcgvYTrbYA2kRkGklv9Tjh4kps4ZgpabnWtq5C73H8zHkIM3gAb99zSjceD1JtNRkCXTys9BfzJiQP63y5Xb/uLJTQRMWYCY1+oVfReyxIa6VmwLpmL++gvlqRitdSGdYMXYV7B6lEbbp0yu+P3BEY+ymuQI1462wIBGe7wfSWwKr76L5NVKqGSJZjTLKxwmoB9rcg9zEAzJF98D82hbfYccALFs3wUt4Af3IncTGozZ4He2c+wFGnOXaBB8TSUcKAf/DgcxRX0Bs0Lngd2kByddGyfzxpntSDdlYSIyzFEsYQ2nO+7RM15MrRlIIYNOqSQUIizh9k4OawBj6iTGfl/KiVay74AaCDY2YvJnb7t64Goeh6tzYm6aFcVGzfet1gO/IPFnHsuwTWLKMBmNKxE7UUetVtNY+mT/eFNh2gGLQRjTB0AZXcP1W+z4/v+cGE0N7sf6MGjaAWy/mL6KGNYY4jTxK7Mm4FtY0wOBloPcvz+wo=
